# Generated by Django 4.2.3 on 2023-08-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recirculer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn_from', models.IntegerField()),
                ('sn_to', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StationStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('people', models.IntegerField(default=0)),
                ('recirculers', models.ManyToManyField(to='Stations.recirculer')),
                ('tickets', models.ManyToManyField(to='Stations.ticket')),
            ],
        ),
    ]
