# Generated by Django 4.2.4 on 2023-08-29 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 29, 14, 5, 56, 69625)),
        ),
    ]
