# Generated by Django 4.2.3 on 2023-08-01 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='sn_from',
            new_name='st_from',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='sn_to',
            new_name='st_to',
        ),
    ]
