# Generated by Django 4.2.3 on 2023-08-01 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stations', '0002_rename_sn_from_ticket_st_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 19, 31, 32, 611231)),
        ),
    ]
